spring:
  application:
    name: weather-crud
  jooq:
    sql-dialect: postgres
  datasource:
    url: jdbc:postgresql://localhost:5432/weather_db
    username: weather_user
    password: weather_pass
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
  flyway:
    enabled: true
    baseline-on-migrate: true
    schemas: public
  cloud:
    feign:
      enabled: true

weatherapi:
  base-url: https://api.weatherapi.com/v1
  key: ${WEATHERAPI_KEY}

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
  pathsToMatch: /api/v1/**
