spring:
  jooq:
    sql-dialect: postgres
  datasource:
    url: jdbc:postgresql://localhost:5432/weather_db
    username: weather_user
    password: weather_pass
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
  flyway:
    enabled: true
    baseline-on-migrate: true
    schemas: public
