version: '3.8'

services:
  postgres:
    image: postgres:17-alpine
    container_name: weather-postgres
    environment:
      POSTGRES_DB: weather_db
      POSTGRES_USER: weather_user
      POSTGRES_PASSWORD: weather_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U weather_user -d weather_db" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    depends_on:
      postgres:
        condition: service_healthy
    build: .
    container_name: weather-app
    #   ДОБАВЬТЕ КЛЮЧ
    environment:
      - WEATHERAPI_KEY=add_key_here
      - DB_HOST=postgres
    ports:
      - "8080:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"


volumes:
  postgres_data:
